version: '2'

services:
  dev:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: weschen/umitest:20190703.7
    container_name: webpack-container
    environment:
      - NODE_ENV=development
      - APIENV=bing.com
    ports:
      - "8080:8000"      
    # volumes:
    #   - .:/src
    #   - /src/node_modules

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: ui-test
    container_name: webpack-test-container
    environment:
      - NODE_ENV=test
    volumes:
      - .:/src
      - /src/node_modules
    command: npm analyze

  prod:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: weschen/umitest:20190703.7
    container_name: prod-container
    environment:
      - NODE_ENV=production
      - APIENV=baidu.com
    ports:
      - "8000:8000"
    # volumes:
    #   - /src/node_modules